--liquibase formatted sql
--changeset betterf:20261007-001-invitations
ALTER TABLE ORGANIZATION ADD COLUMN MAX_ACTIVE_ACCOUNTS INTEGER;
ALTER TABLE ORGANIZATION ADD CONSTRAINT ORGANIZATION_ACCOUNT_CAP CHECK (MAX_ACTIVE_ACCOUNTS > 0);
CREATE TABLE TEAM_INVITATION (
    ID UUID PRIMARY KEY,
    ORGANIZATION_ID UUID NOT NULL REFERENCES ORGANIZATION(ID),
    EMAIL VARCHAR(254) NOT NULL,
    ADMINISTRATOR_NAME VARCHAR(200) NOT NULL,
    ADMINISTRATOR_ID UUID NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TOKEN_HASH VARCHAR(64),
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    ATTEMPTED_AT TIMESTAMPTZ NOT NULL,
    SENT_AT TIMESTAMPTZ,
    SMTP_MESSAGE_ID VARCHAR(255),
    FAILURE_CODE VARCHAR(50),
    CONSTRAINT TEAM_INVITATION_RECIPIENT UNIQUE (ORGANIZATION_ID, EMAIL)
);
CREATE INDEX ACCOUNT_ACTIVE_ORGANIZATION ON ACCOUNT (ORGANIZATION_ID, STATUS);
--rollback DROP TABLE TEAM_INVITATION;
--rollback DROP INDEX ACCOUNT_ACTIVE_ORGANIZATION;
--rollback ALTER TABLE ORGANIZATION DROP COLUMN MAX_ACTIVE_ACCOUNTS;
