-- liquibase formatted sql
-- changeset betterf:20261004-002-email-worker

ALTER TABLE VERIFICATION_EMAIL
    ALTER COLUMN LAST_ATTEMPT_AT DROP NOT NULL,
    ADD COLUMN NEXT_ATTEMPT_AT TIMESTAMPTZ,
    ADD COLUMN CONSECUTIVE_FAILURES INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN ATTEMPT_ID UUID,
    ADD COLUMN SMTP_MESSAGE_ID VARCHAR(255);

-- SMTP acceptance does not establish delivery to the recipient's inbox.
UPDATE VERIFICATION_EMAIL
SET STATUS = 'SMTP_ACCEPTED'
WHERE STATUS = 'SENT';

UPDATE VERIFICATION_EMAIL
SET NEXT_ATTEMPT_AT = CURRENT_TIMESTAMP
WHERE STATUS IN ('PENDING', 'FAILED');

CREATE INDEX VERIFICATION_EMAIL_RETRY
    ON VERIFICATION_EMAIL (NEXT_ATTEMPT_AT, ACCOUNT_ID)
    WHERE STATUS IN ('PENDING', 'FAILED');
