-- liquibase formatted sql
-- changeset betterf:20261004-001-registration

CREATE TABLE ORGANIZATION (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DOMAIN VARCHAR(253) NOT NULL CHECK (DOMAIN = LOWER(DOMAIN)),
    SPECIALIZATION VARCHAR(200) NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

-- Pending rows never reserve a domain; only an active organization owns it.
CREATE UNIQUE INDEX ORGANIZATION_ACTIVE_DOMAIN
    ON ORGANIZATION (DOMAIN)
    WHERE STATUS = 'ACTIVE';

CREATE TABLE ACCOUNT (
    ID UUID PRIMARY KEY,
    EMAIL VARCHAR(254) NOT NULL UNIQUE CHECK (EMAIL = LOWER(EMAIL)),
    FULL_NAME VARCHAR(200) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PROFESSIONAL_ROLE VARCHAR(80) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ORGANIZATION_ID UUID NOT NULL REFERENCES ORGANIZATION (ID),
    ACCESS_ROLE VARCHAR(20),
    UPDATED_AT TIMESTAMPTZ NOT NULL
);

CREATE INDEX ACCOUNT_PENDING_RETENTION
    ON ACCOUNT (UPDATED_AT)
    WHERE STATUS = 'PENDING';

CREATE TABLE VERIFICATION_EMAIL (
    ACCOUNT_ID UUID PRIMARY KEY REFERENCES ACCOUNT (ID),
    RECIPIENT VARCHAR(254) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ATTEMPTS INTEGER NOT NULL DEFAULT 0 CHECK (ATTEMPTS >= 0),
    LAST_ATTEMPT_AT TIMESTAMPTZ NOT NULL,
    LAST_SENT_AT TIMESTAMPTZ,
    FAILURE_CODE VARCHAR(50),
    TOKEN_HASH VARCHAR(64),
    TOKEN_EXPIRES_AT TIMESTAMPTZ,
    CONSTRAINT EMAIL_TOKEN CHECK (
        (
            TOKEN_HASH IS NULL
            AND TOKEN_EXPIRES_AT IS NULL
            AND LAST_SENT_AT IS NULL
        )
        OR (
            TOKEN_HASH IS NOT NULL
            AND TOKEN_EXPIRES_AT IS NOT NULL
            AND LAST_SENT_AT IS NOT NULL
        )
    )
);

-- No automatic destructive rollback: restore a tested backup for data recovery.
