--liquibase formatted sql
--changeset betterf:20261008-001-invitation-acceptance
ALTER TABLE TEAM_INVITATION ADD COLUMN ACCEPTED_AT TIMESTAMPTZ;
ALTER TABLE TEAM_INVITATION ADD COLUMN ACCEPTED_TOKEN_HASH VARCHAR(64);
--rollback ALTER TABLE TEAM_INVITATION DROP COLUMN ACCEPTED_TOKEN_HASH;
--rollback ALTER TABLE TEAM_INVITATION DROP COLUMN ACCEPTED_AT;
