-- liquibase formatted sql
-- changeset foundation:20261007-001-shedlock
CREATE TABLE SHEDLOCK (
    NAME VARCHAR(64) NOT NULL PRIMARY KEY,
    LOCK_UNTIL TIMESTAMP NOT NULL,
    LOCKED_AT TIMESTAMP NOT NULL,
    LOCKED_BY VARCHAR(255) NOT NULL
);
-- rollback DROP TABLE SHEDLOCK;
