-- liquibase formatted sql
-- changeset foundation:20261008-001-refresh-session
CREATE TABLE REFRESH_SESSION (
    ID UUID PRIMARY KEY,
    EMAIL VARCHAR(254) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    PREVIOUS_HASH VARCHAR(64),
    CREDENTIAL_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IDX_REFRESH_SESSION_EXPIRY ON REFRESH_SESSION(EXPIRES_AT);
-- rollback DROP TABLE REFRESH_SESSION;
